export const BLOG_POSTS = [
  {
    id: 1,
    slug: 'future-of-ai-in-enterprise',
    title: 'The Future of AI in Enterprise Solutions',
    excerpt: 'Exploring how artificial intelligence is reshaping business operations and decision-making processes across industries.',
    category: 'AI & ML',
    date: 'Mar 10, 2026',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80',
    content: 'Artificial intelligence is no longer a futuristic concept—it\'s a present-day reality transforming how enterprises operate...',
  },
  {
    id: 2,
    slug: 'microservices-best-practices',
    title: 'Microservices Architecture: Best Practices for 2026',
    excerpt: 'A comprehensive guide to building scalable microservices that drive business agility and technical excellence.',
    category: 'Web Dev',
    date: 'Mar 8, 2026',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    content: 'Microservices architecture has become the de facto standard for building scalable enterprise applications...',
  },
  {
    id: 3,
    slug: 'qa-automation-strategies',
    title: 'Modern QA Automation Strategies for Faster Delivery',
    excerpt: 'How to implement effective QA automation that accelerates development cycles without compromising quality.',
    category: 'QA',
    date: 'Mar 5, 2026',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    content: 'Quality assurance automation is critical for organizations aiming to deliver software faster while maintaining high standards...',
  },
  {
    id: 4,
    slug: 'digital-transformation-healthcare',
    title: 'Digital Transformation in Healthcare: A Case Study',
    excerpt: 'How we helped a healthcare provider modernize their systems and improve patient outcomes.',
    category: 'Industry News',
    date: 'Mar 1, 2026',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    content: 'The healthcare industry is undergoing a massive digital transformation, driven by the need for better patient outcomes...',
  },
  {
    id: 5,
    slug: 'rag-systems-explained',
    title: 'RAG Systems: Building Intelligent Knowledge Bases',
    excerpt: 'Understanding Retrieval-Augmented Generation and its applications in enterprise knowledge management.',
    category: 'AI & ML',
    date: 'Feb 28, 2026',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80',
    content: 'Retrieval-Augmented Generation (RAG) represents a significant advancement in how enterprises can leverage AI...',
  },
  {
    id: 6,
    slug: 'rpa-implementation-guide',
    title: 'RPA Implementation: A Strategic Guide for Enterprises',
    excerpt: 'Key considerations and best practices for successful Robotic Process Automation deployment.',
    category: 'Automation',
    date: 'Feb 25, 2026',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    content: 'Robotic Process Automation (RPA) has emerged as a powerful tool for enterprises looking to streamline operations...',
  },
];
